version: "3.9"

networks:
  incepnet:
    name: incepnet
    driver: bridge

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wp

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/db

  qbittorrent-downloads:
    name: qbittorrent-downloads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/downloads
  qbittorrent-data:
    name: qbittorrent-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/qbittorrent

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - incepnet

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - incepnet
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wp:/var/www/wordpress
    networks:
      - incepnet
    depends_on:
      - wordpress
    ports:
      - "443:443"

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: always
    env_file: .env
    networks:
      - incepnet
    depends_on:
      - nginx
    ports:
      - "6379:6379"

  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/
    restart: always
    env_file: .env
    volumes:
      - wp:/home/$USER
    networks:
      - incepnet
    depends_on:
      - nginx
    ports:
      - "21:21"
      - "21000-21010:21000-21010"

  site:
    container_name: site
    build: requirements/bonus/site/
    restart: always
    networks:
      - incepnet
    depends_on:
      - nginx
    ports:
      - "1111:1111"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    depends_on:
      - mariadb
    networks:
      - incepnet
    ports:
      - "8080:8080"

  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris 
    build: ./requirements/bonus/qBittorrent/
    volumes:
      - qbittorrent-data:/config  # configuration data, this path might need adjustment
      - qbittorrent-downloads:/downloads  # downloaded files
    networks:
      - incepnet
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8081:8081"
    restart: always
    tmpfs:
      - /tmp
    tty: true

